version: '3'
services:
  nginx:
    env_file: .env
    #image: nginx:1.13
    build: ./nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./web:/www/web
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    #image: php:7.2-fpm
    build: ./php
    restart: always
    volumes:
      - ./web:/www/web
    links:
      - mysql
  mysql:
    #image: mysql:5.7
    build: ./mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
